services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        privileged: true
        networks:
            - cicd-net

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        command: tunnel --url http://jenkins:8080 --no-autoupdate
        networks:
            - cicd-net
        depends_on:
            - jenkins

    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        depends_on:
            - db
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
        ports:
            - "9001:9000"
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_extensions:/opt/sonarqube/extensions
        networks:
            - cicd-net

    db:
        image: postgres:15
        container_name: sonar-postgres
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSTGRES_DB=sonar
        volumes:
            - postgresql:/var/lib/postgresql/data
            - postgresql_data:/var/lib/postgresql/data
        networks:
            -cicd-net

volumes:
    jenkins_home:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
    postgresql:
    postgresql_data:

networks:
    cicd-net:
        driver: bridge







